### ISSUE TITLE
After working normally in the solution,I get logged out 

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-auth-dotnet#25]
# Type of issue

- [X] Bug
- [ ] New feature
- [ ] Enhancement

# Description
I didn't do anything special (to my knowledge), just hit refresh page in Chrome.

![image](https://user-images.githubusercontent.com/12633955/30937538-f49a31cc-a38b-11e7-8916-c9ae3d79dcab.png)

Raw text below:
Sign InSorry, but we’re having trouble signing you in.We received a bad request.Additional technical information:Correlation ID: 197537dd-1c47-418a-bcb6-725faad41433Timestamp: 2017-09-27 20:46:07ZAADSTS50011: The reply address 'https://hgtsol12.azurewebsites.net/dashboard' does not match the reply addresses configured for the application: '9eb6d034-99b3-473b-8a3d-6bc915d67b04'. More details: not specified | Additional technical information: | Correlation ID: 197537dd-1c47-418a-bcb6-725faad41433 | Timestamp: 2017-09-27 20:46:07Z | AADSTS50011: The reply address 'https://hgtsol12.azurewebsites.net/dashboard' does not match the reply addresses configured for the application: '9eb6d034-99b3-473b-8a3d-6bc915d67b04'. More details: not specified
-- | -- | -- | -- | --
Additional technical information:
Correlation ID: 197537dd-1c47-418a-bcb6-725faad41433
Timestamp: 2017-09-27 20:46:07Z
AADSTS50011: The reply address 'https://hgtsol12.azurewebsites.net/dashboard' does not match the reply addresses configured for the application: '9eb6d034-99b3-473b-8a3d-6bc915d67b04'. More details: not specified

**Comment by ppathan** [comment]
Fixed
