### ISSUE TITLE
Bad request received after clicking on device details

### ISSUE THREAD

**Issue by hegate** [Azure/pcs-auth-dotnet#28]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
Was exploring chiller 0001 device details and got a bad request, can't enter the solution anymore until I use the landing URL (hector1026.azurewebsites etc.)

![image](https://user-images.githubusercontent.com/12633955/32069372-d4c0e526-ba3d-11e7-9cb9-b4c0d7474894.png)

# Steps to reproduce 

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug 
```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by jillcary** [comment]
It looks like this has since been fixed. I'm not able to repro. Please reopen if you see the issue happen again.
